# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "geometry_x"
version = "0.1.0"
edition = "2018"

[dependencies]
diplomat = "0.2.0"
diplomat-runtime = "0.2.0"
cgmath = "0.18"
insta = "1.7"
